version: '3'

services:
  client-node:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    environment:
      SERVER_DOMEN: http://localhost:443
      CHOKIDAR_USEPOLLING: true
    volumes:
      - ./:/var/www
      - /var/www/node_modules
      - /var/www/.next
    tty: true