version: '3'

services:

  db:
    image: mysql
    container_name: db
    restart: always
    hostname: mysql
    environment:
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: sertificatedb
      MYSQLX: OFF
    ports:
      - 3307:3306

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    restart: always
    container_name: server

    environment:
      PORT: 443
      SECRET_KEY: secretKey
      LOG_FORMAT: dev
      LOG_DIR: ../logs
      ORIGIN: http://localhost:3000
      CREDENTIALS: true
      USER: root
      PASSWORD: root
      DATABASE: sertificatedb
      HOST: db
      NODE_ENV: development
      DOMEN: http://localhost:443
    volumes:
      - ./:/var/www
    ports:
      - 443:443
    expose:
      - 443
    depends_on:
      - db
    links:
      - db
    tty: true
    command: yarn server

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: client
    ports:
      - 3000:3000
    environment:
      SERVER_DOMEN: http://localhost:443
      CHOKIDAR_USEPOLLING: true
    volumes:
      - ./:/var/www
      - /var/www/node_modules
      - /var/www/.next
    depends_on:
      - server
    links:
      - server
    tty: true
    command: yarn client

