version: '3'

services:
  server-node:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: server
    restart: always
    environment:
      PORT: 443
      SECRET_KEY: secretKey
      LOG_FORMAT: dev
      LOG_DIR: ../logs
      ORIGIN: http://localhost:3000
      CREDENTIALS: true
      USER: root
      PASSWORD: root
      DATABASE: sertificatedb
      HOST: 192.168.0.1
      #HOST: localhost
      #HOST: 10.5.0.1
      NODE_ENV: development
      DOMEN: http://localhost:443
    volumes:
      - ./:/var/www
    ports:
      - 443:443
    depends_on:
      - db-node
    tty: true

  db-node:
    image: mysql
    restart: always
    hostname: mysql
    container_name: db
    environment:
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: sertificatedb
      # MYSQL_ROOT_HOST: 10.5.0.1
      MYSQLX: OFF
    ports:
      - 3307:3306
